### ISSUE TITLE
Can't export to Idleon Companion, no data in json

### ISSUE THREAD

**Issue by GeorgeWAmbush** [desophos/idleon-saver#78]
**Describe the problem**
Idelon_Companion doesn't appear to actually be writing anything
Both the Saver and the Game are on my C drive

**Log files**
[logs.zip](https://github.com/desophos/idleon-saver/files/9523248/logs.zip)
Idk if that actually worked.

**Screenshots**
Screenshots won't attach for some reason, but it's an "oops there's an error" when I try to export
Tried multiple formats

**Desktop (please complete the following information):**
Win10 64 bit

**Additional context**
Can't think of any to provide. I went through the steps, tried admin mode, restarted PC and steam.

**Comment by Qt-dev** [comment]
I got something similar on Win11, the main issue seems to be something about the key `mini3a`

```
[ERROR  ] 'mini3a'
Traceback (most recent call last):
  File "main.py", line 120, in try_export
    self.export(fmt)
  File "main.py", line 290, in export
    FirebaseExporter(self.savedata).export(fmt, self.userdir)
  File "idleon_saver\scripts\export.py", line 207, in export
  File "idleon_saver\scripts\export.py", line 219, in save_idleon_companion
  File "idleon_saver\scripts\export.py", line 227, in to_idleon_companion
  File "idleon_saver\scripts\export.py", line 293, in get_cards
  File "idleon_saver\scripts\export.py", line 294, in <dictcomp>
KeyError: 'mini3a'
```
